"""Added pdf_file field to Book model

Revision ID: 6c9a986f8fd8
Revises: 256d205c8884
Create Date: 2025-03-31 18:13:41.926453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c9a986f8fd8'
down_revision = '256d205c8884'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pdf_file_path', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('pdf_file_path')

    # ### end Alembic commands ###
